excluded:
  - "*resource_bundle_accessor*" # SwiftPM Generated
  - ".build"
  - "Package.swift"

opt_in_rules:
  - first_where # Use first(where:) instead of filter().first
  - fatal_error_message # Use fatalError() with a message instead of fatalError()
  - file_header # All files should have a same header.
  - empty_count # Use .isEmpty instead of .count == 0
  - closure_spacing # Closure should have a space before and after the braces
  - contains_over_first_not_nil # Use .contains instead of .first(where:)
  - missing_docs # Required documentation for public functions
  - modifier_order # Modifier order should be consistent
  - convenience_type # Use convenience type instead of type with default values
  - pattern_matching_keywords # Use pattern matching keywords instead of 'is' and 'as'
  - identical_operands # Identical operands should be avoided
  - empty_string # Use .isEmpty instead of .count == 0
  - multiline_parameters # Multiline parameters should be indented the same as the line they are on
  - closure_end_indentation # Closure end should be indented the same as the line the closure starts
  - operator_usage_whitespace # Operator should be surrounded by whitespace
  - closure_parameter_position # Closure parameters should be on the same line as the opening brace
  - collection_alignment # Collection should have the same alignment
  - last_where # Use last(where:) instead of filter().last
  - unused_optional_binding # Unused optional binding should be avoided
  - toggle_bool # use .toggle() instead of !variable
  - explicit_init # .init is not needed
  - fallthrough # fallthrough is not allowed
  - no_fallthrough_only # fallthrough should not be the only statement in a case body
  - comment_spacing # Comments should be followed by a space
  - orphaned_doc_comment # Orphaned doc comment should be avoided
  - local_doc_comment # Local doc comment should be avoided
  - accessibility_label_for_image # Accessibility label for image should be set
  - accessibility_trait_for_button # Accessibility trait for button should be set
  - force_unwrapping # Force unwrapping should be avoided
  - duplicate_imports # Duplicate imports should be avoided

file_header:
  required_pattern: |
    \/\/
    \/\/  .*?\.swift
    \/\/  SwiftExtras
    \/\/
    \/\/  Created by .*? on .*?\.
    \/\/  https:\/\/.*?
    \/\/
    \/\/  https:\/\/github\.com\/0xWDG\/SwiftExtras
    \/\/  MIT License
