name: Run tests on Linux and macOS
on:
  push:
  workflow_dispatch:

jobs:
  test_linux:
    if: true
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: Swift test
        run: swift test

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Select Xcode (Default)"
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Runner environment
        run: |
          echo "MacOS Version"
          sw_vers
          echo "Toolchain version"
          swift -version

      - name: Swift test
        run: swift test
